close all;
clc;

imu4=importdata('implicitdata4.csv');
imu8=importdata('implicitdata8.csv');
exu4=importdata('explicitdata4.csv');
exu8=importdata('explicitdata8.csv');
CNu4=importdata('CNdata4.csv');
CNu8=importdata('CNdata8.csv');
exact4=importdata('exact4.csv');
exact8=importdata('exact8.csv');
errorimp4=importdata('imperror4.csv');
errorimp8=importdata('imperror8.csv');
errorexp4=importdata('experror4.csv');
errorexp8=importdata('CNerror8.csv');
errorCN4=importdata('CNerror4.csv');
errorCN8=importdata('CNerror8.csv');
figure(1);
subplot(2,7,1);mesh(imu4);title('Implicit: 0.4');
subplot(2,7,4);mesh(imu8);title('Implicit: 0.8');
subplot(2,7,7);mesh(exact4);title('Exact: 0.4');
subplot(2,7,8);mesh(errorimp4);title('Implicit Percent Error: 0.4');
subplot(2,7,11);mesh(errorimp8);title('Implicit Percent Error: 0.8');
subplot(2,7,14);mesh(exact8);title('Exact: 0.8');
subplot(2,7,2);mesh(exu4);title('Explicit: 0.4');
subplot(2,7,5);mesh(exu8);title('Explicit: 0.8');
subplot(2,7,9);mesh(errorexp4);title('Explicit Percent Error: 0.4');
subplot(2,7,12);mesh(errorexp8);title('Explicit Percent Error: 0.8');
subplot(2,7,3);mesh(CNu4);title('CN: 0.4');
subplot(2,7,6);mesh(CNu8);title('CN: 0.8');
subplot(2,7,10);mesh(errorCN4);title('CN Percent Error: 0.4');
subplot(2,7,13);mesh(errorCN8);title('CN Percent Error: 0.8');
